### ISSUE TITLE
Problem on run project on Intellij

### ISSUE THREAD

**Issue by M-Razavi** [thomasdarimont/keycloak-extension-playground#17]
I followed the instruction to import the project into the IDE, but when I want to run it, got a ClassNotFound Exception.
it's from KeycloakServer.java:376 `ResteasyDeployment deployment = new ResteasyDeployment();`

`Connected to the target VM, address: '127.0.0.1:54521', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Starting KeycloakPlaygroundServer
../simple-theme/target/theme/
23:21:11,577 INFO  main [org.keycloak.testsuite.KeycloakServer] Using jboss.server.data.dir /tmp/keycloak-server-4631126189321439181/data
Disconnected from the target VM, address: '127.0.0.1:54521', transport: 'socket'
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/resteasy/spi/ResteasyDeployment
	at org.keycloak.testsuite.KeycloakServer.start(KeycloakServer.java:376)
	at org.keycloak.testsuite.KeycloakServer.bootstrapKeycloakServer(KeycloakServer.java:228)
	at com.github.thomasdarimont.keycloak.server.KeycloakPlaygroundServer.main(KeycloakPlaygroundServer.java:19)
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.spi.ResteasyDeployment
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more

Process finished with exit code 1
`

**Comment by M-Razavi** [comment]
it's resolved by removing the `<scope>provided</scope>` from some dependencies
